### ISSUE TITLE
query with account fails

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#426]
When I set an account on the viem simulate call I get the `Error: NotStaticCall()` which is because its failing the `tx.origin == address(0)` check. If account isn't set I think it defaults to zero address for account and it all works fine.
I think it matches tx.origin to the account used. 

Can run in [this example](https://github.com/balancer/b-sdk/blob/add-account-to-query-debug/examples/swaps/customSwap.ts).

Using `simulate`, with an optional `account` param passed for user. See [code](https://github.com/balancer/b-sdk/blob/add-account-to-query-debug/src/entities/swap/swaps/v3/index.ts#L122):
```
await routerContract.simulate.querySwapSingleTokenExactIn(
  [
      this.swaps.pool,
      this.swaps.tokenIn,
      this.swaps.tokenOut,
      this.swaps.exactAmountIn,
      DEFAULT_USERDATA,
  ],
  { blockNumber: block, account },
```

According to docs simulate: 
```
/**
* Simulates/validates a contract interaction. This is useful for retrieving return data and revert reasons of contract write functions.
*
* This function does not require gas to execute and does not change the state of the blockchain. It is almost identical to [`readContract`](https://viem.sh/docs/contract/readContract), but also supports contract write functions.
*
* Internally, `simulate` uses a [Public Client](https://viem.sh/docs/clients/public) to call the [`call` action](https://viem.sh/docs/actions/public/call) with [ABI-encoded `data`](https://viem.sh/docs/contract/encodeFunctionData).
*
```

It works if no account is set (default to zero) or zero passed manually.

Error message when account passed:
```
ContractFunctionExecutionError: The contract function "querySwapSingleTokenExactIn" reverted.

Error: NotStaticCall()
 
Contract Call:
  address:   0xDd10aDF05379D7C0Ee4bC9c72ecc5C01c40E25b8
  function:  querySwapSingleTokenExactIn(address pool, address tokenIn, address tokenOut, uint256 exactAmountIn, bytes userData)
  args:                                 (0x6D9656174205876897A9f526CCDcD3aE725ffEFF, 0xE8d4E9Fc8257B77Acb9eb80B5e8176F4f0cBCeBC, 0xF0Bab79D87F51a249AFe316a580C1cDFC111bE10, 7000000000000000000, 0x)
  sender:    0x5036388C540994Ed7b74b82F71175a441F85BdA1

Docs: https://viem.sh/docs/contract/simulateContract
Version: viem@2.12.1
    at getContractError (/Users/jg/Documents/code/b-sdk/node_modules/.pnpm/viem@2.12.1_typescript@5.3.3/node_modules/viem/utils/errors/getContractError.ts:72:10)
    at simulateContract (/Users/jg/Documents/code/b-sdk/node_modules/.pnpm/viem@2.12.1_typescript@5.3.3/node_modules/viem/actions/public/simulateContract.ts:265:27)
    ... 3 lines matching cause stack trace ...
    at executeExample (/Users/jg/Documents/code/b-sdk/examples/lib/executeExample.ts:6:5) {
  details: undefined,
  docsPath: '/docs/contract/simulateContract',
  metaMessages: [
    'Error: NotStaticCall()',
    ' ',
    'Contract Call:',
    '  address:   0xDd10aDF05379D7C0Ee4bC9c72ecc5C01c40E25b8\n' +
      '  function:  querySwapSingleTokenExactIn(address pool, address tokenIn, address tokenOut, uint256 exactAmountIn, bytes userData)\n' +
      '  args:                                 (0x6D9656174205876897A9f526CCDcD3aE725ffEFF, 0xE8d4E9Fc8257B77Acb9eb80B5e8176F4f0cBCeBC, 0xF0Bab79D87F51a249AFe316a580C1cDFC111bE10, 7000000000000000000, 0x)\n' +
      '  sender:    0x5036388C540994Ed7b74b82F71175a441F85BdA1'
  ],
  shortMessage: 'The contract function "querySwapSingleTokenExactIn" reverted.',
  version: 'viem@2.12.1',
  cause: ContractFunctionRevertedError: The contract function "querySwapSingleTokenExactIn" reverted.
  
  Error: NotStaticCall()
  
  Version: viem@2.12.1
      at <anonymous> (/Users/jg/Documents/code/b-sdk/node_modules/.pnpm/viem@2.12.1_typescript@5.3.3/node_modules/viem/utils/errors/getContractError.ts:62:14)
      at getContractError (/Users/jg/Documents/code/b-sdk/node_modules/.pnpm/viem@2.12.1_typescript@5.3.3/node_modules/viem/utils/errors/getContractError.ts:70:5)
      at simulateContract (/Users/jg/Documents/code/b-sdk/node_modules/.pnpm/viem@2.12.1_typescript@5.3.3/node_modules/viem/actions/public/simulateContract.ts:265:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at SwapV3.querySingleSwap (/Users/jg/Documents/code/b-sdk/src/entities/swap/swaps/v3/index.ts:122:23)
      at customSwap (/Users/jg/Documents/code/b-sdk/examples/swaps/customSwap.ts:51:26)
      at executeExample (/Users/jg/Documents/code/b-sdk/examples/lib/executeExample.ts:6:5) {
    details: undefined,
    docsPath: undefined,
    metaMessages: [ 'Error: NotStaticCall()', '' ],
    shortMessage: 'The contract function "querySwapSingleTokenExactIn" reverted.',
    version: 'viem@2.12.1',
    data: { abiItem: [Object], args: undefined, errorName: 'NotStaticCall' },
    reason: undefined,
    signature: undefined
  },
  abi: [...cut this out to keep shorter
  ],
  args: [
    '0x6D9656174205876897A9f526CCDcD3aE725ffEFF',
    '0xE8d4E9Fc8257B77Acb9eb80B5e8176F4f0cBCeBC',
    '0xF0Bab79D87F51a249AFe316a580C1cDFC111bE10',
    7000000000000000000n,
    '0x'
  ],
  contractAddress: '0xDd10aDF05379D7C0Ee4bC9c72ecc5C01c40E25b8',
  formattedArgs: undefined,
  functionName: 'querySwapSingleTokenExactIn',
  sender: '0x5036388C540994Ed7b74b82F71175a441F85BdA1'
}
/Users/jg/Documents/code/b-sdk/src/entities/swap/swaps/v3/index.ts:188
        throw Error('Unsupported V3 Query');
              ^


Error: Unsupported V3 Query
    at SwapV3.querySingleSwap (/Users/jg/Documents/code/b-sdk/src/entities/swap/swaps/v3/index.ts:188:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at customSwap (/Users/jg/Documents/code/b-sdk/examples/swaps/customSwap.ts:51:26)
    at executeExample (/Users/jg/Documents/code/b-sdk/examples/lib/executeExample.ts:6:5)
```

**Comment by johngrantuk** [comment]
Closing in favour of #438
